# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-33706ffc-082c-4470-8e43-8fa1d071179e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-33706ffc-082c-4470-8e43-8fa1d071179e".device = "/dev/disk/by-uuid/33706ffc-082c-4470-8e43-8fa1d071179e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9EBE-244A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-af0953e8-4082-4b8e-be3b-d147df43a908"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
